### ISSUE TITLE
Exporter displaces overlapping meshes, breaking physics shapes and uses strange rotation.

### ISSUE THREAD

**Issue by DerRidda** [alrusdi/leadwerks-blender-exporter#1]
I'm trying to export a model with a mesh named collision but any kind of overlapping mesh will eventually be moved in relation to the other mesh, essentially making it impossible to export something with collision.

On top of that, if I use multiple, disjoint meshes for collision, they all get recognized but essentially displaced and rotated randomly.

Also, the imported Mesh is strangely rotated around every axis, even though the local coordinates in blender are properly aligned.

**Comment by alrusdi** [comment]
Can you provide a sample .blend file to test it?

**Comment by DerRidda** [comment]
https://drive.google.com/file/d/0B3jPhxJap2Y3RnRJbGIyNFhxUzA/edit?usp=sharing

**Comment by alrusdi** [comment]
I can confirm the problem.
Workaround for now is to Apply rotation and scale for each model in hierarchy (Crl+A).
it's not comfortable and i will see what can i do to fix it

**Comment by alrusdi** [comment]
Thanks everyone who helped me to resolve this issue. It was a kinda big deal)
